services:
  toll:
    image: toll
    build:
      context: ./toll
    deploy:
      restart_policy:
        condition: always
        delay: 10s
        window: 120s
    volumes:
      - /home/desi/desicars/desiworker/toll/logs/:/container/logs/
    command: python3 main.py --read-only
  rentacar:
    image: rentacar
    build:
      context: ./rentacar
    volumes:
      - /home/desi/desicars/desiworker/rentacar/logs/:/rentcar/logs/
    command: python3 main.py --read-only
