FROM python:3.12

COPY . /contrainer
WORKDIR /contrainer
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
RUN apt update -y
RUN apt install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils
RUN apt install -y google-chrome-stable
RUN pip3 install -r requirements.txt
RUN mkdir logs/
RUN mkdir downloads/

ENTRYPOINT ["python3", "main.py"]
CMD ["python3", "main.py"]